[package]
name = "peace_item_file_download"
description = "Manages downloading a file for the peace framework"
documentation = "https://docs.rs/peace_item_file_download/"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
doctest = false
test = false

[dependencies]
bytes = { workspace = true }
cfg-if = { workspace = true }
futures = { workspace = true }
miette = { workspace = true, optional = true }
peace = { workspace = true, default-features = false }
reqwest = { workspace = true, features = ["stream"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["net", "time", "rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true }

[features]
default = []
error_reporting = ["peace/error_reporting"]
output_progress = ["peace/output_progress"]
item_interactions = ["peace/item_interactions"]
