/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_workspaceandoutput_free: (a: number, b: number) => void;
export const __wbg_get_workspaceandoutput_output: (a: number) => [number, number];
export const __wbg_set_workspaceandoutput_output: (a: number, b: number, c: number) => void;
export const wasm_init: (a: number, b: number, c: number, d: number) => any;
export const wasm_fetch: (a: number) => any;
export const wasm_status: (a: number) => any;
export const wasm_goal: (a: number) => any;
export const wasm_diff: (a: number) => any;
export const wasm_ensure_dry: (a: number) => any;
export const wasm_ensure: (a: number) => any;
export const wasm_clean_dry: (a: number) => any;
export const wasm_clean: (a: number) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const closure2980_externref_shim: (a: number, b: number, c: any) => void;
export const closure3194_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
