/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_workspaceandoutput_free(a: number): void;
export function __wbg_get_workspaceandoutput_output(a: number, b: number): void;
export function __wbg_set_workspaceandoutput_output(a: number, b: number, c: number): void;
export function wasm_init(a: number, b: number, c: number, d: number): number;
export function wasm_fetch(a: number): number;
export function wasm_status(a: number): number;
export function wasm_goal(a: number): number;
export function wasm_diff(a: number): number;
export function wasm_ensure_dry(a: number): number;
export function wasm_ensure(a: number): number;
export function wasm_clean_dry(a: number): number;
export function wasm_clean(a: number): number;
export function __wbg_intounderlyingbytesource_free(a: number): void;
export function intounderlyingbytesource_type(a: number, b: number): void;
export function intounderlyingbytesource_autoAllocateChunkSize(a: number): number;
export function intounderlyingbytesource_start(a: number, b: number): void;
export function intounderlyingbytesource_pull(a: number, b: number): number;
export function intounderlyingbytesource_cancel(a: number): void;
export function __wbg_intounderlyingsink_free(a: number): void;
export function intounderlyingsink_write(a: number, b: number): number;
export function intounderlyingsink_close(a: number): number;
export function intounderlyingsink_abort(a: number, b: number): number;
export function __wbg_intounderlyingsource_free(a: number): void;
export function intounderlyingsource_pull(a: number, b: number): number;
export function intounderlyingsource_cancel(a: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h9b7b72dccaa7e135(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h84b06de9ccd79fbf(a: number, b: number, c: number, d: number): void;
