[book]
authors = ["Azriel Hoh"]
language = "en"
multilingual = false
src = "src"
title = "The Peace Framework"

[rust]
edition = "2021"

[preprocessor.graphviz]
command = "mdbook-graphviz"

[output.html]
theme = "theme"
additional-css = [
    "src/css/layout.css",
    "src/css/presentation.css",
    "src/css/terminal.css",
]
additional-js = ["src/js/highlightjs-line-numbers.min.js"]
cname = "peace.mk"
git-repository-url = "https://github.com/azriel91/peace"
edit-url-template = "https://github.com/azriel91/peace/edit/main/doc/{path}"
site-url = "/book/" # to work with `peace_website`

[output.html.fold]
enable = true
level = 1

[output.html.code]
hidelines = { bash = "~", cs = "~", java = "#" }
