[package]
name = "peace_rt_model_core"
description = "Core runtime traits for the peace automation framework."
documentation = "https://docs.rs/peace_rt_model_core/"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
doctest = false
test = false

[dependencies]
async-trait = { workspace = true }
cfg-if = { workspace = true }
indexmap = { workspace = true }
indicatif = { workspace = true, features = ["tokio"] }
miette = { workspace = true, optional = true }
peace_cmd_model = { workspace = true }
peace_core = { workspace = true }
peace_flow_model = { workspace = true }
peace_fmt = { workspace = true }
peace_item_interaction_model = { workspace = true, optional = true }
peace_item_model = { workspace = true }
peace_params = { workspace = true }
peace_profile_model = { workspace = true }
peace_progress_model = { workspace = true, optional = true }
peace_resource_rt = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
type_reg = { workspace = true, features = ["resman"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
base64 = { workspace = true }

[features]
default = []
error_reporting = ["dep:miette", "peace_cmd_model/error_reporting"]
output_in_memory = ["indicatif/in_memory"]
output_progress = [
    "dep:peace_item_interaction_model",
    "dep:peace_progress_model",
    "peace_item_interaction_model/output_progress",
]
