[package]
name = "peace_item_tar_x"
description = "Manages extracting a tar file for the peace framework"
documentation = "https://docs.rs/peace_item_tar_x/"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
doctest = false
test = false

[dependencies]
derivative = { workspace = true }
miette = { workspace = true, optional = true }
peace = { workspace = true, default-features = false }
serde = { workspace = true, features = ["derive"] }
# We use this instead of tokio-tar, because:
#
# * We expect tar extraction to be a compute operation.
# * tokio-tar is not actively maintained / released.
# * tokio-tar depends on tokio's "io" feature, which does not support WASM.
#
# Asynchronous IO can be handled using [SyncIoBridge].
#
# [SyncIoBridge]: https://docs.rs/tokio-util/latest/tokio_util/io/struct.SyncIoBridge.html
tar = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = { workspace = true }
tokio = { workspace = true, features = ["fs"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true }

[features]
default = []
error_reporting = ["peace/error_reporting"]
output_progress = ["peace/output_progress"]
resource_interactions = ["peace/resource_interactions"]
